export const DataForTablePagination = [
    {
        id: 1,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 2,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 3,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 4,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 5,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 6,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 7,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 8,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 9,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 10,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 11,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 12,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 13,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 14,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 15,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 16,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 17,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 18,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 19,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 20,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 21,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 22,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 23,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 24,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 25,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 26,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 27,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 28,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 29,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 30,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 31,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 32,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 33,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 34,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 35,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 36,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 37,
        name: 'John',
        lastName: 'Smith',
        email: 'test@test.com',
    },
    {
        id: 38,
        name: 'John2',
        lastName: 'Smith2',
        email: 'test@test.com2',
    },
    {
        id: 39,
        name: 'John3',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
    {
        id: 40,
        name: 'John40',
        lastName: 'Smith3',
        email: 'test@test.com3',
    },
];
